Repository abdullahashfaq-ds/GPA-Calculator, pull requests merged in 2024-10, with the labels that each got.

#6 Updated Components Styling
  app/static/js/scripts.js
  app/templates/calculator.html
  app/templates/home.html
  app/templates/navbar.html
  app/templates/policy.html
  app/templates/result.html
Labels: frontend

#7 Fixed Calculator & PDF Logic Issues
  app/templates/calculator.html
  app/templates/home.html
  app/templates/policy.html
  app/templates/result.html
Labels: backend, frontend

#8 Updated README File
  README.md
Labels: documentation
